#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:10:00
#SBATCH -J LovisaLittbrand_RNAtrimming
#SBATCH --mail-type=ALL
#SBATCH --mail-user lollo.littbrand@hotmail.com

#Loading appropriate modules for RNA trimming
module load bioinfo-tools
module load trimmomatic

#Trimming files: SRR4342137.1 and SRR4342137.2
trimmomatic PE -threads 2 -phred33 /home/lovilitt/Genome_Analysis/raw_data/RNA_untrimmed/SRR4342137.1.fastq.gz \
/home/lovilitt/Genome_Analysis/raw_data/RNA_untrimmed/SRR4342137.2.fastq.gz \
/home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/SRR4342137.1.trim_paired.fastq.gz \
/home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/SRR4342137.1.trim_unpaired.fastq.gz \
/home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/SRR4342137.2.trim_paired.fastq.gz \
/home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/SRR4342137.2.trim_unpaired.fastq.gz \
ILLUMINACLIP:$TRIMMOMATIC_HOME/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:30 MINLEN:50

#Trimming files: SRR4342139.1 and SRR4342139.2
trimmomatic PE -threads 2 -phred33 /home/lovilitt/Genome_Analysis/raw_data/RNA_untrimmed/SRR4342139.1.fastq.gz \
/home/lovilitt/Genome_Analysis/raw_data/RNA_untrimmed/SRR4342139.2.fastq.gz \
/home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/SRR4342139.1.trim_paired.fastq.gz \
/home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/SRR4342139.1.trim_unpaired.fastq.gz \
/home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/SRR4342139.2.trim_paired.fastq.gz \
/home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/SRR4342139.2.trim_unpaired.fastq.gz \
ILLUMINACLIP:$TRIMMOMATIC_HOME/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:30 MINLEN:50

