#!/bin/bash -l
#This file contains the code for checking the quality of the trimmed RNA reads

#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:25:00
#SBATCH -J LovisaLittbrand_QC_RNAtrimmed
#SBATCH --mail-type=ALL
#SBATCH --mail-user lollo.littbrand@hotmail.com

#Loading appropriate modules for quality check
module load bioinfo-tools
module load FastQC/0.11.8

#Commands for running quality control on trimmed reads
fastqc -t 2 -f fastq -o /home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/FastQC_RNA_trimmed_2 /home/lovilitt/Genome_Analysis/analyses/02_RNATrimmed/RNATrimmed_2/*.fastq.gz

