#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 08:00:00
#SBATCH -J LovisaLittbrand_phylogeny
#SBATCH --mail-type=ALL
#SBATCH --mail-user lollo.littbrand@hotmail.com

#Loading all appropriate modules
module load bioinfo-tools
module load phylophlan
module load FastTree
module load usearch/5.2.32
module load biopython
module load muscle

#Directory of where results will be stored
outdir = /home/lovilitt/Genome_Analysis/analyses/10a_phylogeny

#Creating directories needed for Phylophlan
mkdir -p $outdir/input/metagenome
mkdir -p $outdir/output
mkdir -p $outdir/data/ppaalns

#Symlinks to input data files
#Enough with folder or specify file from annotation???
for folder in /home/lovilitt/Genome_Analysis/analyses/07a_annotation/*
do
 ln -sf $folder $outdir/input/metagenome/
done

#Symlinks phylophlan data files
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/*.bz2 $outdir/data/
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppaalns/*.bz2 $outdir/data/ppaalns/
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppafull.tax.txt $outdir/data/
ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/taxcuration/ $outdir/taxcuration

#Phylophlan needs to be run from specific directory
cd $outdir

#Commands for running phylophlan
phylophlan -t -i metagenome --nproc 2

