#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J Plot_binning_eval
#SBATCH --mail-type=ALL
#SBATCH --mail-user lollo.littbrand@hotmail.com

#loading appropriate modules
module load bioinfo-tools
module load CheckM/1.0.12

#Commands for running the analysis
checkm bin_qa_plot -x fa /home/lovilitt/Genome_Analysis/analyses/06a_binning_eval/checkM /home/lovilitt/Genome_Analysis/analyses/05a_binning /home/lovilitt/Genome_Analysis/analyses/06a_binning_eval/checkM/plot




